<?php
namespace App\Services;
use App\Models\GoogleCalendarConnection;use Google\Client;use Google\Service\Calendar;use Google\Service\Oauth2;use RuntimeException;
class GoogleCalendarService
{
public function isConfigured():bool{return filled(config('google-calendar.client_id'))&&filled(config('google-calendar.client_secret'))&&filled(config('google-calendar.redirect_uri'));}
private function client():Client{if(!$this->isConfigured())throw new RuntimeException('Google Calendar integration has not been configured on the server.');$c=new Client();$c->setClientId(config('google-calendar.client_id'));$c->setClientSecret(config('google-calendar.client_secret'));$c->setRedirectUri(config('google-calendar.redirect_uri'));$c->setScopes([Calendar::CALENDAR_EVENTS_READONLY,Calendar::CALENDAR_CALENDARLIST_READONLY,'openid','email','profile']);$c->setAccessType('offline');$c->setPrompt('consent');return$c;}
public function authUrl(string $state):string{$c=$this->client();$c->setState($state);return$c->createAuthUrl();}
public function connect(string $code,int $userId):GoogleCalendarConnection{$c=$this->client();$token=$c->fetchAccessTokenWithAuthCode($code);if(isset($token['error']))throw new RuntimeException($token['error_description']??$token['error']);$c->setAccessToken($token);$me=(new Oauth2($c))->userinfo->get();$old=GoogleCalendarConnection::latest()->first();return GoogleCalendarConnection::updateOrCreate(['id'=>$old?->id],['connected_by_user_id'=>$userId,'google_account_id'=>$me->id,'google_account_name'=>$me->name,'google_account_email'=>$me->email,'access_token'=>$token,'refresh_token'=>$token['refresh_token']??$old?->refresh_token,'token_expires_at'=>now()->addSeconds($token['expires_in']??3600),'scopes'=>explode(' ',$token['scope']??''),'is_active'=>true,'connected_at'=>now(),'last_error'=>null]);}
private function ready(GoogleCalendarConnection $x):Client{$c=$this->client();$c->setAccessToken($x->access_token);if($c->isAccessTokenExpired()){if(!$x->refresh_token)throw new RuntimeException('Google Calendar must be reconnected.');$token=$c->fetchAccessTokenWithRefreshToken($x->refresh_token);if(isset($token['error']))throw new RuntimeException('Google Calendar must be reconnected.');$x->update(['access_token'=>$token,'token_expires_at'=>now()->addSeconds($token['expires_in']??3600),'last_refreshed_at'=>now(),'last_error'=>null]);}return$c;}
public function calendars(GoogleCalendarConnection $x):array{$items=(new Calendar($this->ready($x)))->calendarList->listCalendarList()->getItems();return array_map(fn($i)=>['id'=>$i->id,'name'=>$i->summary,'primary'=>(bool)$i->primary,'selected'=>in_array($i->id,$x->selected_calendar_ids??[],true)],$items);}
public function events(GoogleCalendarConnection $x,array $ids,string $start,string $end):array{$api=new Calendar($this->ready($x));$names=collect($this->calendars($x))->keyBy('id');$out=[];foreach($ids as$id)foreach($api->events->listEvents($id,['timeMin'=>$start,'timeMax'=>$end,'singleEvents'=>true,'orderBy'=>'startTime'])->getItems()as$e)$out[]=['id'=>'google-'.sha1($id.'-'.$e->id),'title'=>$e->summary?:'(Untitled event)','start'=>$e->start->dateTime?:$e->start->date,'end'=>$e->end->dateTime?:$e->end->date,'allDay'=>(bool)$e->start->date,'sourceType'=>'google_calendar','editable'=>false,'extendedProps'=>['calendarId'=>$id,'calendarName'=>$names[$id]['name']??$id,'location'=>$e->location,'description'=>$e->description,'organiser'=>$e->organizer?->displayName?:$e->organizer?->email,'htmlLink'=>$e->htmlLink]];$x->update(['last_refreshed_at'=>now(),'last_error'=>null]);return$out;}
}
