<?php
namespace Tests\Feature;
use App\Models\{Permission,User,UserPermission};use Database\Seeders\PermissionsSeeder;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\Hash;use Tests\TestCase;
class UserManagementWorkflowTest extends TestCase
{
use RefreshDatabase;protected function setUp():void{parent::setUp();$this->seed(PermissionsSeeder::class);}
private function admin():User{return User::factory()->create(['role'=>'admin','is_active'=>true]);}
private function payload(array $extra=[]):array{return array_merge(['name'=>'Test','email'=>'test@test.com','password'=>'password','password_confirmation'=>'password','role'=>'custom','is_active'=>true,'permissions'=>['dashboard.view'=>true,'clients.view'=>true]],$extra);}
public function test_custom_user_is_created_atomically_with_hashed_password_and_grants():void{$response=$this->actingAs($this->admin())->postJson('/api/users',$this->payload())->assertCreated()->assertJsonPath('role','custom')->assertJsonPath('is_active',true)->assertJsonPath('effective_permission_count',2);$user=User::findOrFail($response->json('id'));$this->assertTrue(Hash::check('password',$user->password));$this->assertCount(2,UserPermission::where('user_id',$user->id)->where('allowed',true)->get());$this->assertTrue($user->hasPermission('dashboard.view'));$this->assertDatabaseHas('permission_audit_logs',['affected_user_id'=>$user->id,'action'=>'user.created']);}
public function test_standard_role_stores_only_differing_overrides():void{$defaults=Permission::pluck('key')->mapWithKeys(fn($key)=>[$key=>false])->all();$defaults['clients.view']=true;$response=$this->actingAs($this->admin())->postJson('/api/users',$this->payload(['email'=>'tech@test.com','role'=>'technician','permissions'=>$defaults]))->assertCreated();$user=User::find($response->json('id'));$this->assertTrue($user->hasPermission('clients.view'));$this->assertFalse($user->hasPermission('job_cards.view'));$this->assertDatabaseHas('user_permissions',['user_id'=>$user->id,'permission_id'=>Permission::where('key','job_cards.view')->value('id'),'allowed'=>false]);$this->assertDatabaseMissing('user_permissions',['user_id'=>$user->id,'permission_id'=>Permission::where('key','clients.view')->value('id')]);}
public function test_user_creation_validation_and_authorisation():void{$admin=$this->admin();$this->actingAs($admin)->postJson('/api/users',$this->payload(['password_confirmation'=>'different']))->assertUnprocessable()->assertJsonValidationErrors('password');$this->actingAs($admin)->postJson('/api/users',$this->payload(['role'=>'invalid']))->assertUnprocessable()->assertJsonValidationErrors('role');$this->actingAs($admin)->postJson('/api/users',$this->payload(['permissions'=>['missing.permission'=>true]]))->assertUnprocessable()->assertJsonValidationErrors('permissions');User::factory()->create(['email'=>'test@test.com']);$this->actingAs($admin)->postJson('/api/users',$this->payload())->assertUnprocessable()->assertJsonValidationErrors('email');$this->actingAs(User::factory()->create(['role'=>'custom','is_active'=>true]))->postJson('/api/users',$this->payload(['email'=>'other@test.com']))->assertForbidden();}
}
