// Pure Firestore-doc -> Postgres-row mapping table for Phase A of
// migrate-firestore-to-postgres.mjs. Deliberately zero-dependency (no firebase-admin, no
// @supabase/supabase-js) so it can be unit-tested without installing anything or touching
// real Firestore/Supabase -- see entityMappings.test.mjs.
//
// `id` is NOT reused from Firestore doc IDs -- a fresh uuid is generated by Postgres and
// the Firestore doc ID is kept in `legacy_firestore_id` so the relink phase can re-point
// foreign keys. Keys prefixed `_legacy_` are FK markers consumed by the caller before
// insert (never real Postgres columns -- must be stripped, or insert() will error).
export const ENTITY_COLLECTIONS = [
  { collection: "clients", table: "clients", map: (d) => ({
    company_name: d.company_name ?? "", contact_person: d.contact_person ?? null,
    email: d.email ?? null, phone: d.phone ?? null, address: d.address ?? null,
    notes: d.notes ?? null, is_active: d.is_active ?? true,
  }) },
  { collection: "machines", table: "machines", map: (d) => ({
    brand: d.brand ?? null, model: d.model ?? null, serial_number: d.serial_number ?? null,
    machine_type: d.machine_type ?? null, refrigerant_type: d.refrigerant_type ?? null,
    installation_date: d.installation_date ?? null, notes: d.notes ?? null,
    _legacy_client_id: d.client_id != null ? String(d.client_id) : null,
  }) },
  { collection: "service_records", table: "service_records", map: (d) => ({
    technician_name: d.technician_name ?? null, status: d.status ?? null,
    next_service_due: d.next_service_due ?? null, notes: d.notes ?? null,
    _legacy_machine_id: d.machine_id != null ? String(d.machine_id) : null,
  }) },
  { collection: "job_cards", table: "job_cards", map: (d) => ({
    status: d.status ?? "Open", fault_description: d.fault_description ?? null,
    technician_name: d.technician_name ?? null, technician_notes: d.technician_notes ?? null,
    arrival_condition: d.arrival_condition ?? null, date_completed: d.date_completed ?? null,
    _legacy_client_id: d.client_id != null ? String(d.client_id) : null,
    _legacy_machine_id: d.machine_id != null ? String(d.machine_id) : null,
  }) },
  { collection: "job_card_lines", table: "job_card_lines", map: (d) => ({
    line_type: d.line_type ?? "Labour", description: d.description ?? "",
    quantity: d.quantity ?? 1, unit_price: d.unit_price ?? 0, line_total: d.line_total ?? 0,
    _legacy_job_card_id: d.job_card_id != null ? String(d.job_card_id) : null,
  }) },
  { collection: "knowledge_machines", table: "knowledge_machines", map: (d) => ({
    name: d.name ?? "", model: d.model ?? null, description: d.description ?? null,
  }) },
  // Added 2026-08-03 (Phase 2 prep) -- these four collections are confirmed live via
  // frontend/src/api/apiClient.js's routeCollections and entities.js's KnowledgeBaseService
  // but were missing from this table entirely, so no data would have been migrated for
  // them and the users-phase relink of knowledge_notes.created_by would have errored
  // against a nonexistent legacy_firestore_id column. See
  // supabase/migrations/0006_knowledge_legacy_ids.sql for the column that makes the
  // relink possible.
  { collection: "knowledge_notes", table: "knowledge_notes", map: (d) => ({
    title: d.title ?? null, body: d.body ?? null,
    _legacy_knowledge_machine_id: d.knowledge_machine_id != null ? String(d.knowledge_machine_id) : null,
  }) },
  { collection: "knowledge_service_codes", table: "knowledge_service_codes", map: (d) => ({
    code: d.code ?? "", description: d.description ?? null,
    _legacy_knowledge_machine_id: d.knowledge_machine_id != null ? String(d.knowledge_machine_id) : null,
  }) },
  { collection: "knowledge_media", table: "knowledge_media", map: (d) => ({
    storage_path: d.storage_path ?? "", caption: d.caption ?? null,
    _legacy_knowledge_machine_id: d.knowledge_machine_id != null ? String(d.knowledge_machine_id) : null,
  }) },
  { collection: "knowledge_documents", table: "knowledge_documents", map: (d) => ({
    storage_path: d.storage_path ?? "", title: d.title ?? null,
    _legacy_knowledge_machine_id: d.knowledge_machine_id != null ? String(d.knowledge_machine_id) : null,
  }) },
];

// Every legacy-marker key that might appear in a mapped row, across all entities above.
// The caller destructures these out before insert() -- kept in one place so adding a new
// entity with a new _legacy_* marker can't silently leak an unknown column into Postgres.
export const LEGACY_MARKER_KEYS = [
  "_legacy_client_id",
  "_legacy_machine_id",
  "_legacy_job_card_id",
  "_legacy_knowledge_machine_id",
];

export function stripLegacyMarkers(mappedRow) {
  const columns = { ...mappedRow };
  const legacy = {};
  for (const key of LEGACY_MARKER_KEYS) {
    legacy[key] = columns[key] ?? null;
    delete columns[key];
  }
  return { columns, legacy };
}
