<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up():void{
if(Schema::hasTable('knowledge_machines')&&!Schema::hasTable('knowledge_documents')){Schema::disableForeignKeyConstraints();foreach(['knowledge_service_codes','knowledge_media','knowledge_notes','knowledge_machines'] as $table)Schema::dropIfExists($table);Schema::enableForeignKeyConstraints();}
Schema::create('knowledge_machines',function(Blueprint $t){$t->id();$t->string('manufacturer');$t->string('model_name');$t->string('variant')->nullable();$t->string('product_code')->nullable()->unique();$t->string('category')->nullable();$t->text('summary')->nullable();$t->json('supported_refrigerants')->nullable();$t->json('technical_specifications')->nullable();$t->json('main_functions')->nullable();$t->boolean('is_active')->default(true);$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->index(['manufacturer','model_name']);});
Schema::create('knowledge_notes',function(Blueprint $t){$t->id();$t->foreignId('knowledge_machine_id')->constrained()->cascadeOnDelete();$t->string('title');$t->string('note_type');$t->longText('content');$t->boolean('is_pinned')->default(false);$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
Schema::create('knowledge_media',function(Blueprint $t){$t->id();$t->foreignId('knowledge_machine_id')->constrained()->cascadeOnDelete();$t->foreignId('knowledge_note_id')->nullable()->constrained()->nullOnDelete();$t->string('original_filename');$t->string('stored_filename');$t->string('storage_disk')->default('local');$t->string('file_path');$t->string('mime_type');$t->unsignedBigInteger('file_size');$t->string('caption')->nullable();$t->string('alt_text')->nullable();$t->foreignId('uploaded_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
Schema::create('knowledge_service_codes',function(Blueprint $t){$t->id();$t->foreignId('knowledge_machine_id')->constrained()->cascadeOnDelete();$t->string('function_name');$t->text('description')->nullable();$t->text('service_code');$t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();$t->foreignId('updated_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();$t->unique(['knowledge_machine_id','function_name'],'kb_service_function_unique');});
Schema::create('knowledge_documents',function(Blueprint $t){$t->id();$t->foreignId('knowledge_machine_id')->constrained()->cascadeOnDelete();$t->string('title');$t->string('original_filename');$t->string('storage_disk')->default('local');$t->string('file_path');$t->string('mime_type');$t->unsignedBigInteger('file_size');$t->foreignId('uploaded_by')->nullable()->constrained('users')->nullOnDelete();$t->timestamps();});
Schema::create('audit_logs',function(Blueprint $t){$t->id();$t->foreignId('user_id')->nullable()->constrained()->nullOnDelete();$t->string('action');$t->string('entity_type');$t->unsignedBigInteger('entity_id')->nullable();$t->json('metadata')->nullable();$t->string('ip_address',45)->nullable();$t->timestamp('created_at')->useCurrent();$t->index(['entity_type','entity_id']);});
} public function down():void{foreach(['audit_logs','knowledge_documents','knowledge_service_codes','knowledge_media','knowledge_notes','knowledge_machines'] as $table)Schema::dropIfExists($table);}};
