import { useCallback, useEffect, useState } from "react";
import { apiClient } from "@/api/apiClient";import { useAuth } from "@/lib/AuthContext";import { Button } from "@/components/ui/button";import { Checkbox } from "@/components/ui/checkbox";
export default function SystemSettings(){
  const{hasPermission}=useAuth();const[status,setStatus]=useState(null),[calendars,setCalendars]=useState([]),[message,setMessage]=useState(""),[connecting,setConnecting]=useState(false);
  const load=useCallback(async()=>{const current=await apiClient.request('/google-calendar/status');setStatus(current);setCalendars(current.connected?await apiClient.request('/google-calendar/calendars'):[])},[]);
  useEffect(()=>{const result=new URLSearchParams(window.location.search).get('google_calendar');if(result==='connected')setMessage('Google Calendar connected successfully.');if(result==='error')setMessage('Google Calendar could not be connected. Please try again.');load().catch(e=>setMessage(e.message))},[load]);
  const connect=async()=>{setConnecting(true);setMessage("");try{const response=await apiClient.request('/google-calendar/connect');if(!response.authorization_url)throw new Error('The server did not return a Google authorization URL.');window.location.assign(response.authorization_url)}catch(error){setMessage(error.message)}finally{setConnecting(false)}};
  const save=async()=>{try{await apiClient.request('/google-calendar/calendars',{method:'PUT',body:JSON.stringify({calendar_ids:calendars.filter(c=>c.selected).map(c=>c.id)})});setMessage('Selected calendars saved.');await load()}catch(e){setMessage(e.message)}};
  const disconnect=async()=>{try{await apiClient.request('/google-calendar/disconnect',{method:'DELETE'});setMessage('Google Calendar disconnected.');await load()}catch(e){setMessage(e.message)}};
  return <div className="max-w-3xl space-y-5"><div><h1 className="text-2xl font-bold">System Settings</h1><p className="text-muted-foreground">Manage secure external integrations.</p></div>{message&&<div className="rounded-xl border p-3 text-sm">{message}</div>}<section className="rounded-2xl border bg-card p-6 space-y-4"><h2 className="text-lg font-bold">Google Calendar</h2>{!status?<p>Loading connection status…</p>:!status.connected?<><p>Google Calendar is not connected.</p><p className="text-sm text-muted-foreground">Connect the authorised company Google account to display selected calendar events in the CAP Dashboard. The integration is read-only and will not change the Google Calendar.</p>{hasPermission('calendar.google.connect')&&<Button onClick={connect} disabled={connecting}>{connecting?'Connecting…':'Connect Google Calendar'}</Button>}</>:<><dl className="grid grid-cols-[160px_1fr] gap-2 text-sm"><dt>Connection Status</dt><dd>Connected</dd><dt>Account</dt><dd>{status.account_name||'—'} ({status.account_email})</dd><dt>Connection Date</dt><dd>{status.connected_at||'—'}</dd><dt>Last Refresh</dt><dd>{status.last_refreshed_at||'Not refreshed yet'}</dd></dl>{status.requires_reconnection&&<p className="text-destructive">Google Calendar must be reconnected.</p>}<div className="space-y-2">{calendars.map((calendar,index)=><label className="flex items-center gap-2" key={calendar.id}><Checkbox checked={calendar.selected} onCheckedChange={value=>setCalendars(calendars.map((item,itemIndex)=>itemIndex===index?{...item,selected:!!value}:item))}/>{calendar.name}{calendar.primary?' (Primary)':''}</label>)}</div><div className="flex flex-wrap gap-2">{hasPermission('calendar.google.calendars.select')&&<Button onClick={save}>Change Selected Calendars</Button>}{hasPermission('calendar.google.connect')&&<Button variant="outline" onClick={connect} disabled={connecting}>{connecting?'Connecting…':'Replace Connection'}</Button>}{hasPermission('calendar.google.disconnect')&&<Button variant="destructive" onClick={disconnect}>Disconnect</Button>}</div></>}</section></div>
}
