<?php
namespace App\Http\Controllers;
use App\Models\{PermissionAuditLog,User};use Illuminate\Http\{JsonResponse,Request,Response};use Illuminate\Validation\Rule;
class AdminUserController extends Controller{
public function index(Request $r):JsonResponse{return response()->json(User::orderBy('name')->get()->map(fn($u)=>$this->safe($u)));}
public function store(Request $r):JsonResponse{$this->need($r,'users.create');$d=$this->valid($r);$u=User::create($d);PermissionAuditLog::create(['changed_by_user_id'=>$r->user()->id,'affected_user_id'=>$u->id,'action'=>'user.created','metadata'=>['role'=>$u->role]]);return response()->json($this->safe($u),201);}
public function show(Request $r,User $user):JsonResponse{return response()->json($this->safe($user));}
public function update(Request $r,User $user):JsonResponse{$this->need($r,'users.edit');$d=$this->valid($r,$user);$roleChanged=isset($d['role'])&&$d['role']!==$user->role;$statusChanged=isset($d['is_active'])&&(bool)$d['is_active']!==$user->is_active;if($roleChanged)$this->need($r,'users.roles.manage');if($statusChanged)$this->need($r,'users.disable');$this->guard($user,$d);$user->update($d);if($statusChanged&&!$user->is_active)$user->tokens()->delete();if($roleChanged||$statusChanged)PermissionAuditLog::create(['changed_by_user_id'=>$r->user()->id,'affected_user_id'=>$user->id,'action'=>$roleChanged?'user.role_changed':($user->is_active?'user.enabled':'user.disabled'),'metadata'=>['role'=>$user->role,'is_active'=>$user->is_active]]);return response()->json($this->safe($user->fresh()));}
public function status(Request $r,User $user):JsonResponse{$this->need($r,'users.disable');$d=$r->validate(['is_active'=>['required','boolean']]);$this->guard($user,$d);$user->update($d);if(!$user->is_active)$user->tokens()->delete();PermissionAuditLog::create(['changed_by_user_id'=>$r->user()->id,'affected_user_id'=>$user->id,'action'=>$user->is_active?'user.enabled':'user.disabled','metadata'=>[]]);return response()->json($this->safe($user->fresh()));}
public function destroy(Request $r,User $user):Response{$this->need($r,'users.delete');$this->guard($user,['is_active'=>false]);$user->update(['is_active'=>false]);$user->tokens()->delete();return response()->noContent();}
private function valid(Request $r,?User $u=null):array{return $r->validate(['name'=>[$u?'sometimes':'required','string','max:255'],'email'=>[$u?'sometimes':'required','email',Rule::unique('users')->ignore($u)],'password'=>[$u?'sometimes':'required','string','min:8','confirmed'],'role'=>[$u?'sometimes':'required',Rule::in(['admin','technician','accountant','custom'])],'is_active'=>['sometimes','boolean'],'must_change_password'=>['sometimes','boolean']]);}
private function need(Request $r,string $key):void{abort_unless($r->user()->hasPermission($key),403);}
private function guard(User $u,array $d):void{if($u->role==='admin'&&$u->is_active&&(($d['role']??'admin')!=='admin'||isset($d['is_active'])&&!$d['is_active'])){$others=User::where('role','admin')->where('is_active',true)->whereKeyNot($u->id)->get()->filter(fn($x)=>$x->hasPermission('users.permissions.manage')&&$x->hasPermission('users.roles.manage'))->count();abort_if($others<1,422,'The final qualifying administrator cannot be disabled or demoted.');}}
private function safe(User $u):array{return['id'=>$u->id,'name'=>$u->name,'email'=>$u->email,'role'=>$u->role,'is_active'=>$u->is_active,'must_change_password'=>$u->must_change_password,'effective_permission_count'=>count($u->getEffectivePermissions()),'updated_at'=>$u->updated_at];}}
