<?php
namespace App\Http\Controllers;
use App\Models\{GoogleCalendarConnection,GoogleOauthState};use App\Services\GoogleCalendarService;use Illuminate\Http\{JsonResponse,RedirectResponse,Request};use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
class GoogleCalendarController extends Controller
{
private function current():?GoogleCalendarConnection{return GoogleCalendarConnection::where('is_active',true)->latest()->first();}
private function safe(?GoogleCalendarConnection $x):array{return['connected'=>(bool)$x,'requires_reconnection'=>(bool)$x?->last_error,'account_name'=>$x?->google_account_name,'account_email'=>$x?->google_account_email,'connected_at'=>$x?->connected_at,'last_refreshed_at'=>$x?->last_refreshed_at,'selected_calendars'=>$x?->selected_calendar_ids??[],'last_error'=>$x?->last_error];}
public function status():JsonResponse{return response()->json($this->safe($this->current()));}
public function connect(Request $r,GoogleCalendarService $service):JsonResponse{if(!$service->isConfigured())return response()->json(['message'=>'Google Calendar integration has not been configured on the server.'],422);$state=Str::random(64);GoogleOauthState::where('expires_at','<',now())->delete();GoogleOauthState::create(['state_hash'=>hash('sha256',$state),'user_id'=>$r->user()->id,'redirect_url'=>config('google-calendar.frontend_success_url'),'expires_at'=>now()->addMinutes(10)]);return response()->json(['authorization_url'=>$service->authUrl($state)]);}
public function callback(Request $r,GoogleCalendarService $service):RedirectResponse{$failure=config('google-calendar.frontend_error_url');if($r->filled('error')||!$r->filled('state')||!$r->filled('code'))return redirect()->away($failure);$state=DB::transaction(function()use($r){$row=GoogleOauthState::where('state_hash',hash('sha256',$r->string('state')))->whereNull('consumed_at')->lockForUpdate()->first();if(!$row||$row->expires_at->isPast())return null;$row->update(['consumed_at'=>now()]);return$row;});if(!$state)return redirect()->away($failure);try{$service->connect($r->string('code'),$state->user_id);return redirect()->away($state->redirect_url?:config('google-calendar.frontend_success_url'));}catch(\Throwable $e){report($e);return redirect()->away($failure);}}
public function calendars(GoogleCalendarService $g):JsonResponse{$x=$this->current();return response()->json($x?$g->calendars($x):[]);}
public function select(Request $r):JsonResponse{$d=$r->validate(['calendar_ids'=>['required','array'],'calendar_ids.*'=>['string','max:1024']]);$x=$this->current();abort_unless($x,409,'Google Calendar is not connected.');$x->update(['selected_calendar_ids'=>array_values(array_unique($d['calendar_ids']))]);return response()->json($this->safe($x->fresh()));}
public function disconnect():JsonResponse{$x=$this->current();if($x)$x->update(['is_active'=>false,'access_token'=>['revoked'=>true],'refresh_token'=>null]);return response()->json(['connected'=>false]);}
}
