<?php
namespace App\Http\Controllers; use App\Models\{KnowledgeDocument,KnowledgeMachine,KnowledgeMedia}; use App\Support\Audit; use Illuminate\Http\{JsonResponse,Request,Response}; use Illuminate\Support\Facades\Storage; use Illuminate\Support\Str; use Symfony\Component\HttpFoundation\StreamedResponse;
class KnowledgeFileController extends Controller {
public function mediaIndex(KnowledgeMachine $knowledgeMachine):JsonResponse{return response()->json($knowledgeMachine->media()->latest()->get());}
public function mediaStore(Request $r,KnowledgeMachine $knowledgeMachine):JsonResponse{$this->write($r);$r->validate(['files'=>['required','array','max:10'],'files.*'=>['file','max:10240','mimetypes:image/jpeg,image/png,image/webp,image/heic,image/heif'],'caption'=>['nullable','string','max:255'],'alt_text'=>['nullable','string','max:255'],'knowledge_note_id'=>['nullable','integer','exists:knowledge_notes,id']]);$created=[];try{foreach($r->file('files') as $file){$name=Str::uuid().'.'.strtolower($file->extension());$path=$file->storeAs("knowledge-base/{$knowledgeMachine->id}/media",$name,'local');$created[]=KnowledgeMedia::create(['knowledge_machine_id'=>$knowledgeMachine->id,'knowledge_note_id'=>$r->input('knowledge_note_id'),'original_filename'=>$file->getClientOriginalName(),'stored_filename'=>$name,'storage_disk'=>'local','file_path'=>$path,'mime_type'=>$file->getMimeType(),'file_size'=>$file->getSize(),'caption'=>$r->caption,'alt_text'=>$r->alt_text,'uploaded_by'=>$r->user()->id]);}return response()->json($created,201);}catch(\Throwable $e){foreach($created as $m){Storage::disk($m->storage_disk)->delete($m->file_path);$m->delete();}throw $e;}}
public function mediaFile(Request $r,KnowledgeMedia $knowledgeMedia):StreamedResponse{return Storage::disk($knowledgeMedia->storage_disk)->response($knowledgeMedia->file_path,$knowledgeMedia->original_filename,['Content-Type'=>$knowledgeMedia->mime_type,'Content-Disposition'=>'inline']);}
public function mediaDestroy(Request $r,KnowledgeMedia $knowledgeMedia):Response{$this->write($r);Storage::disk($knowledgeMedia->storage_disk)->delete($knowledgeMedia->file_path);$knowledgeMedia->delete();return response()->noContent();}
public function documentIndex(KnowledgeMachine $knowledgeMachine):JsonResponse{return response()->json($knowledgeMachine->documents()->latest()->get());}
public function documentStore(Request $r,KnowledgeMachine $knowledgeMachine):JsonResponse{$this->write($r,true);$r->validate(['file'=>['required','file','max:20480','mimetypes:application/pdf'],'title'=>['required','string','max:255']]);$f=$r->file('file');$name=Str::uuid().'.pdf';$path=$f->storeAs("knowledge-base/{$knowledgeMachine->id}/documents",$name,'local');try{$d=KnowledgeDocument::create(['knowledge_machine_id'=>$knowledgeMachine->id,'title'=>$r->title,'original_filename'=>$f->getClientOriginalName(),'storage_disk'=>'local','file_path'=>$path,'mime_type'=>'application/pdf','file_size'=>$f->getSize(),'uploaded_by'=>$r->user()->id]);Audit::record($r,'knowledge_document.uploaded',$d);return response()->json($d,201);}catch(\Throwable $e){Storage::disk('local')->delete($path);throw $e;}}
public function documentFile(Request $r,KnowledgeDocument $knowledgeDocument):StreamedResponse{return Storage::disk($knowledgeDocument->storage_disk)->response($knowledgeDocument->file_path,$knowledgeDocument->original_filename,['Content-Type'=>'application/pdf','Content-Disposition'=>'inline']);}
public function documentDestroy(Request $r,KnowledgeDocument $knowledgeDocument):Response{$this->write($r,true);Storage::disk($knowledgeDocument->storage_disk)->delete($knowledgeDocument->file_path);Audit::record($r,'knowledge_document.deleted',$knowledgeDocument);$knowledgeDocument->delete();return response()->noContent();}
private function write(Request $r,bool $admin=false):void{abort_unless($admin?$r->user()->role==='admin':in_array($r->user()->role,['admin','technician']),403);}}
