-- Adds legacy_firebase_uid to public.users, mirroring the legacy_firestore_id columns
-- added in 0003_legacy_migration_ids.sql. Needed because public.users.id is generated by
-- Supabase Auth (auth.users.id, a fresh uuid) and cannot simply reuse a Firebase Auth UID
-- (Firebase UIDs are ~28-char alphanumeric strings, not valid uuids) -- so anything that
-- referenced a Firestore users/{uid} document (e.g. knowledge_notes.created_by) needs this
-- mapping to be re-linked after import. Used by
-- supabase/scripts/migrate-firestore-to-postgres.mjs's user-migration pass.

alter table public.users add column legacy_firebase_uid text unique;
create index users_legacy_firebase_uid_idx on public.users (legacy_firebase_uid);
